# ============================================================================
# Automated Test Setup Script for TimelapseCapture
# ============================================================================

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "TimelapseCapture Test Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if we're in the right directory
if (-not (Test-Path "TimelapseCapture.csproj")) {
    Write-Host "ERROR: TimelapseCapture.csproj not found" -ForegroundColor Red
    Write-Host "Please run this script from the TimelapseCapture project directory" -ForegroundColor Yellow
    exit 1
}

Write-Host "Found TimelapseCapture.csproj" -ForegroundColor Green

# Check if test project already exists
if (Test-Path "TimelapseCapture.Tests") {
    Write-Host "Test project already exists" -ForegroundColor Yellow
    $response = Read-Host "Delete and recreate? (y/N)"
    if ($response -eq 'y' -or $response -eq 'Y') {
        Write-Host "Removing existing test project..." -ForegroundColor Yellow
        Remove-Item "TimelapseCapture.Tests" -Recurse -Force
    } else {
        Write-Host "Aborting" -ForegroundColor Yellow
        exit 0
    }
}

# Create test project directory
Write-Host ""
Write-Host "Creating test project directory..." -ForegroundColor Cyan
New-Item -ItemType Directory -Path "TimelapseCapture.Tests" | Out-Null

# Create .csproj file for .NET 9 Windows
Write-Host "Creating .NET 9 Windows test project..." -ForegroundColor Cyan

$csprojContent = @'
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimelapseCapture.csproj" />
  </ItemGroup>

</Project>
'@

Set-Content -Path "TimelapseCapture.Tests\TimelapseCapture.Tests.csproj" -Value $csprojContent -Encoding UTF8
Write-Host "Created TimelapseCapture.Tests.csproj" -ForegroundColor Green

# Create test file
Write-Host "Creating test files..." -ForegroundColor Cyan

$testContent = @'
// ============================================================================
// STARTER TEST SUITE FOR TIMELAPSECAPTURE
// Auto-generated by setup-tests.ps1
// ============================================================================

using Xunit;
using FluentAssertions;
using System;
using System.Drawing;
using System.IO;

namespace TimelapseCapture.Tests
{
    public class SessionManagerTests : IDisposable
    {
        private readonly string _testDirectory;

        public SessionManagerTests()
        {
            _testDirectory = Path.Combine(
                Path.GetTempPath(),
                "TimelapseTests",
                Guid.NewGuid().ToString());
            Directory.CreateDirectory(_testDirectory);
        }

        [Fact]
        public void CreateNamedSession_WithValidParameters_CreatesCompleteStructure()
        {
            // Arrange
            string sessionName = "TestSession";
            var region = new Rectangle(0, 0, 1920, 1080);

            // Act
            string sessionFolder = SessionManager.CreateNamedSession(
                _testDirectory,
                sessionName,
                intervalSeconds: 5,
                imageFormat: "JPEG",
                jpegQuality: 90,
                region: region,
                videoFps: 30);

            // Assert
            Directory.Exists(sessionFolder).Should().BeTrue("session folder should exist");
            Directory.Exists(Path.Combine(sessionFolder, "frames")).Should().BeTrue("frames folder should exist");
            Directory.Exists(Path.Combine(sessionFolder, "output")).Should().BeTrue("output folder should exist");
        }

        [Fact]
        public void CreateNamedSession_SavesCorrectMetadata()
        {
            // Arrange
            var region = new Rectangle(100, 200, 1920, 1080);

            // Act
            string sessionFolder = SessionManager.CreateNamedSession(
                _testDirectory, "MetadataTest", 10, "PNG", 100, region, 24);

            var session = SessionManager.LoadSession(sessionFolder);

            // Assert
            session.Should().NotBeNull();
            session!.Name.Should().Be("MetadataTest");
            session.IntervalSeconds.Should().Be(10);
        }

        [Fact]
        public void IncrementFrameCount_IncreasesCountByOne()
        {
            // Arrange
            var sessionFolder = SessionManager.CreateNamedSession(
                _testDirectory, "IncrementTest", 5, "JPEG", 90, 
                new Rectangle(0, 0, 1920, 1080), 30);
            
            // Act
            SessionManager.IncrementFrameCount(sessionFolder);
            
            // Assert
            var session = SessionManager.LoadSession(sessionFolder);
            session!.FramesCaptured.Should().Be(1);
        }

        [Fact]
        public void LoadSession_WithNonExistentPath_ReturnsNull()
        {
            // Arrange
            string fakePath = Path.Combine(_testDirectory, "DoesNotExist");

            // Act
            var session = SessionManager.LoadSession(fakePath);

            // Assert
            session.Should().BeNull("loading non-existent session should return null");
        }

        [Fact]
        public void FindActiveSession_WithNoActiveSessions_ReturnsNull()
        {
            // Arrange
            var session1Folder = SessionManager.CreateNamedSession(
                _testDirectory, "Inactive1", 5, "JPEG", 90, 
                new Rectangle(0, 0, 1920, 1080), 30);
            var session1 = SessionManager.LoadSession(session1Folder);
            session1!.Active = false;
            SessionManager.SaveSession(session1Folder, session1);

            // Act
            var result = SessionManager.FindActiveSession(_testDirectory);

            // Assert
            result.Should().BeNull("should return null when no active sessions exist");
        }

        public void Dispose()
        {
            try
            {
                if (Directory.Exists(_testDirectory))
                    Directory.Delete(_testDirectory, recursive: true);
            }
            catch { }
        }
    }

    public class ValidationHelperTests
    {
        [Theory]
        [InlineData(1920, 1080, true)]
        [InlineData(1921, 1080, false)]
        [InlineData(0, 1080, false)]
        public void IsValidRegion_ValidatesDimensions(int width, int height, bool expected)
        {
            // Arrange
            var region = new Rectangle(0, 0, width, height);
            
            // Act
            var result = ValidationHelper.IsValidRegion(region);
            
            // Assert
            result.Should().Be(expected, 
                $"region {width}x{height} should be {(expected ? "valid" : "invalid")}");
        }
    }
}
'@

Set-Content -Path "TimelapseCapture.Tests\BasicTests.cs" -Value $testContent -Encoding UTF8
Write-Host "Created BasicTests.cs" -ForegroundColor Green

# Add test project to solution if solution exists
if (Test-Path "TimelapseCapture.sln") {
    Write-Host ""
    Write-Host "Adding test project to solution..." -ForegroundColor Cyan
    dotnet sln TimelapseCapture.sln add TimelapseCapture.Tests\TimelapseCapture.Tests.csproj
    Write-Host "Test project added to solution" -ForegroundColor Green
}

# Restore packages for test project only
Write-Host ""
Write-Host "Restoring NuGet packages..." -ForegroundColor Cyan
Push-Location TimelapseCapture.Tests
dotnet restore
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Package restore failed" -ForegroundColor Red
    Pop-Location
    exit 1
}
Pop-Location

# Build ONLY the test project (not the whole solution)
Write-Host ""
Write-Host "Building test project..." -ForegroundColor Cyan
Push-Location TimelapseCapture.Tests
dotnet build --configuration Debug

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Build failed" -ForegroundColor Red
    Pop-Location
    exit 1
}

Write-Host "Build successful" -ForegroundColor Green

# Run tests
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Running Tests" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

dotnet test --configuration Debug --verbosity normal

Pop-Location

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "SUCCESS! All tests passed!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "You now have 6 working tests covering:" -ForegroundColor Cyan
    Write-Host "  - SessionManager (5 tests)" -ForegroundColor White
    Write-Host "  - ValidationHelper (1 test with 3 scenarios)" -ForegroundColor White
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "1. View tests: TimelapseCapture.Tests\BasicTests.cs" -ForegroundColor White
    Write-Host "2. Run tests anytime: cd TimelapseCapture.Tests && dotnet test" -ForegroundColor White
    Write-Host "3. See SETUP_TESTING.md for detailed guide" -ForegroundColor White
    Write-Host "4. Copy tests from artifacts for more coverage" -ForegroundColor White
    Write-Host ""
    Write-Host "To run with coverage:" -ForegroundColor Cyan
    Write-Host "  cd TimelapseCapture.Tests" -ForegroundColor White
    Write-Host "  dotnet test /p:CollectCoverage=true" -ForegroundColor White
} else {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Yellow
    Write-Host "Some tests failed" -ForegroundColor Yellow
    Write-Host "========================================" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "This is actually GOOD - tests found bugs!" -ForegroundColor Green
    Write-Host "The tests are working correctly by detecting issues." -ForegroundColor White
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "1. Review test failures above" -ForegroundColor White
    Write-Host "2. Fix the bugs in your code" -ForegroundColor White
    Write-Host "3. Re-run: cd TimelapseCapture.Tests && dotnet test" -ForegroundColor White
    Write-Host "4. Repeat until all tests pass" -ForegroundColor White
}

Write-Host ""
Write-Host "Test setup complete!" -ForegroundColor Cyan
